<div class="row">
    <div class="col-md-12 text-center social-footer">
        <a href="" title="" target="_blank"><span class='fa fa-facebook'></span></a>
        <a href="" title="" target="_blank"><span class='fa fa-twitter'></span></a>
        <a href="" title="" target="_blank"><span class='fa fa-google-plus'></span></a>
        <a href="" title="" target="_blank"><span class='fa fa-instagram'></span></a>
        <a href="" title="" target="_blank"><span class='fa fa-youtube'></span></a>
        <a href="" title="" target="_blank"><span class='fa fa-pinterest'></span></a>
    </div>
</div>